name: Deploy To GitHub Pages
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: StudioKarsa/studiokarsa.github.io
          publish_branch: master
          publish_dir: ./public
          cname: studiokarsa.tech
